name: Deploy to Cloud Run Without Testing

on:
  push:
    branches: [main]

env:
  PROJECT_ID: new-cicd-study
  REGION: asia-southeast2
  ARTIFACT_REGISTRY: my-docker-repo
  ARTIFACT_LOCATION: asia-southeast2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build and Push
        run: |
          docker build -t asia-southeast2-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/app:${{ github.sha }} .
          docker push asia-southeast2-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/app:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy app \
            --image asia-southeast2-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/app:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
