name: Deploy to Cloud Run Without Testing
on:
  push:
    branches: [ main ]
env:
  PROJECT_ID: study-cicd2024
  REGION: asia-southeast2
  ARTIFACT_REGISTRY: theapp

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        token_format: 'access_token'
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Configure Docker
      run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet
      
    - name: Build and Push
      run: |
        docker build -t asia-southeast2-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/app:${{ github.sha }} .
        docker push asia-southeast2-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/app:${{ github.sha }}
        
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy app \
          --image asia-southeast2-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/app:${{ github.sha }} \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated
