name: Test and Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: kinetic-keep-465215-s1
  REGION: asia-southeast2
  ARTIFACT_REGISTRY: my-docker-repo
  ARTIFACT_LOCATION: asia-southeast2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build and Push
        run: |
          docker build -t asia-southeast2-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/app:${{ github.sha }} .
          docker push asia-southeast2-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/app:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy app \
            --image asia-southeast2-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/app:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
